import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { ReduxProvider } from "@/components/providers/Redux";
import { Aside } from "@/components/common/Aside";
import { cn } from "@/helpers/cn";
import { ToastProvider } from "@/components/providers/Toast";
import { getCookie } from "@/helpers/getCookie";
import { getPathname } from "@/helpers/getPathname";
import { Modals } from "@/components/Modals";

const inter = Inter({
    variable: "--font-inter",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    preload: true,
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: ReactNode;
}

const RootLayout = async ({ children }: Readonly<RootLayoutProps>) => {
    const token = await getCookie("token");
    const pathname = await getPathname();

    let isAuthorized;

    if (!token || !token.length) {
        isAuthorized = false;
    } else {
        try {
            /* const profile = await getProfile(); */

            /* if ("email" in profile) {
                isAuthorized = true;
            } else {
                isAuthorized = false;
            } */
            isAuthorized = false;
        } catch (error) {
            console.log(error);
            isAuthorized = false;
        }
    }

    return (
        <html lang="en">
            <body
                className={cn(
                    !pathname.includes("quest-completing")
                        ? "grid grid-cols-[320px_1fr] relative"
                        : "",
                    inter.variable,
                )}
            >
                <ReduxProvider>
                    {!pathname.includes("quest-completing") && (
                        <Aside isAuthorized={isAuthorized} />
                    )}
                    <main
                        className={
                            !pathname.includes("quest-completing") ? "p-12" : ""
                        }
                    >
                        {children}
                    </main>
                    <div className="fixed -z-10 bg-[#8C55FE] bg-opacity-40 w-[550px] h-[550px] -left-[160px] top-0 blur-[500px]"></div>
                    <div className="fixed -z-10 bg-[#00D1FF] bg-opacity-20 w-[550px] h-[550px] left-[50%] top-[50%] blur-[500px] -translate-x-[50%]"></div>
                    <div className="fixed -z-10 bg-[#BD00FF] bg-opacity-20 w-[550px] h-[550px] -right-[150px] -bottom-[100px] blur-[500px]"></div>
                    <Modals />
                    <ToastProvider />
                </ReduxProvider>
            </body>
        </html>
    );
};

export default RootLayout;
