import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const inter = Inter({
    variable: "--font-inter",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    preload: true,
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: ReactNode;
}

const RootLayout = ({ children }: Readonly<RootLayoutProps>) => {
    return (
        <html lang="en">
            <body className={inter.variable}>
                {/* <Aside />
                <Header /> */}
                <main>{children}</main>
                {/* <Footer /> */}
            </body>
        </html>
    );
};

export default RootLayout;
