import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { ReduxProvider } from "@/components/providers/Redux";
import { Aside } from "@/components/common/Aside";
import { cn } from "@/helpers/cn";
import { ToastProvider } from "@/components/providers/Toast";
import { getCookie } from "@/helpers/getCookie";
import { getProfile } from "@/api/auth";

const inter = Inter({
    variable: "--font-inter",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    preload: true,
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: ReactNode;
}

const RootLayout = async ({ children }: Readonly<RootLayoutProps>) => {
    const token = await getCookie("token");

    let isAuthorized;

    if (!token || !token.length) {
        isAuthorized = false;
    } else {
        try {
            const profile = await getProfile();

            if ("email" in profile) {
                isAuthorized = true;
            } else {
                isAuthorized = false;
            }
        } catch (error) {
            console.log(error);
            isAuthorized = false;
        }
    }

    return (
        <html lang="en">
            <body
                className={cn(
                    "grid grid-cols-[minmax(320px,420px)_1fr]",
                    inter.variable,
                )}
            >
                <ReduxProvider>
                    <div className="fixed -z-10 bg-[#8C55FE] bg-opacity-40 w-[550px] h-[550px] -left-[160px] top-0 blur-[500px]"></div>
                    <Aside isAuthorized={isAuthorized} />
                    <main className="p-12">{children}</main>
                    <ToastProvider />
                </ReduxProvider>
            </body>
        </html>
    );
};

export default RootLayout;
