import { UserProfilePageComponent } from "@/components/page-components/UserProfile";
import { Profile } from "@/types/user.interface";

const profile: Profile = {
    id: "1",
    email: "testuser@example.com",
    firstName: "Test",
    lastName: "User",
    rating: 5,
    createdQuests: [
        {
            id: "quest1",
            title: "Adventure in the Forest",
            description: "Explore the mysterious forest and solve puzzles.",
            rating: 4.8,
            imageUrl: "/test.png",
            createdAt: "2024-02-08T12:00:00Z",
            owner: {
                id: "1",
                email: "testuser@example.com",
                firstName: "Test",
                lastName: "User",
                rating: 4.5,
                avatar: null,
            },
            timesPlayed: 120,
            timeLimit: 30,
            reviews: [],
            questions: [],
        },
        {
            id: "quest1",
            title: "Adventure in the Forest",
            description: "Explore the mysterious forest and solve puzzles.",
            rating: 4.8,
            imageUrl: "/test.png",
            createdAt: "2024-02-08T12:00:00Z",
            owner: {
                id: "1",
                email: "testuser@example.com",
                firstName: "Test",
                lastName: "User",
                rating: 4.5,
                avatar: null,
            },
            timesPlayed: 120,
            timeLimit: 30,
            reviews: [],
            questions: [],
        },
        {
            id: "quest1",
            title: "Adventure in the Forest",
            description: "Explore the mysterious forest and solve puzzles.",
            rating: 4.8,
            imageUrl: "/test.png",
            createdAt: "2024-02-08T12:00:00Z",
            owner: {
                id: "1",
                email: "testuser@example.com",
                firstName: "Test",
                lastName: "User",
                rating: 4.5,
                avatar: null,
            },
            timesPlayed: 120,
            timeLimit: 30,
            reviews: [],
            questions: [],
        },
        {
            id: "quest1",
            title: "Adventure in the Forest",
            description: "Explore the mysterious forest and solve puzzles.",
            rating: 4.8,
            imageUrl: "/test.png",
            createdAt: "2024-02-08T12:00:00Z",
            owner: {
                id: "1",
                email: "testuser@example.com",
                firstName: "Test",
                lastName: "User",
                rating: 4.5,
                avatar: null,
            },
            timesPlayed: 120,
            timeLimit: 30,
            reviews: [],
            questions: [],
        },
    ],
    avatar: null,
    completedQuests: [
        {
            id: "quest2",
            title: "Mystery of the Lost Treasure",
            description: "Find the lost treasure hidden deep in the mountains.",
            rating: 4.7,
            imageUrl: "/test.png",
            createdAt: "2024-02-07T15:00:00Z",
            owner: {
                id: "2",
                email: "questowner@example.com",
                firstName: "Test",
                lastName: "User",
                rating: 4.9,
                avatar: null,
            },
            timesPlayed: 200,
            timeLimit: 45,
            reviews: [],
            accuracy: 85,
            questions: [],
        },
        {
            id: "quest3",
            title: "Escape from the Haunted Mansion",
            description: "Solve the clues and escape from the haunted mansion.",
            rating: 4.5,
            imageUrl: "/test.png",
            createdAt: "2024-02-06T18:00:00Z",
            owner: {
                id: "3",
                email: "hauntedmaster@example.com",
                firstName: "Test",
                lastName: "User",
                rating: 4.6,
                avatar: null,
            },
            timesPlayed: 150,
            timeLimit: 60,
            reviews: [],
            accuracy: 72,
            questions: [],
        },
    ],
};

const UserProfile = () => {
    return <UserProfilePageComponent profile={profile} />;
};

export default UserProfile;
